name: groceries_app
description: A demo application for Widgetbook and how to implement a design system from Figma.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^9.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  google_fonts: ^5.1.0
  widgetbook_annotation: ^3.0.0
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  widgetbook:
    git:
      url: https://github.com/widgetbook/widgetbook.git
      ref: main
      path: packages/widgetbook
  widgetbook_generator: ^3.0.0
  build_runner: ^2.4.5


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fruits/